### ISSUE TITLE
Missing conf file in 5.3.2

### ISSUE THREAD

**Issue by fprina** [florianutz/ubuntu2004_cis#16]
**Describe the bug**
According to the 5.3.2 section it's also needed `account required pam_tally2.so` in the /etc/pam.d/common-account files
Without this line Pam_tally2 counter increases every time sudo 

**Additional context**
this is my current patch

```
- name: "SCORED | 5.3.2 | PATCH | Ensure lockout for failed password attempts is configured"
  block:
      - name: "SCORED | 5.3.2 | PATCH |  Ensure lockout for failed password attempts is configured - /etc/pam.d/common-account"
        lineinfile:
            dest: /etc/pam.d/common-account
            line: 'account required pam_tally2.so'

      - name: "SCORED | 5.3.2 | PATCH |  Ensure lockout for failed password attempts is configured - /etc/pam.d/common-auth"
        lineinfile:
            dest: /etc/pam.d/common-auth
            line: 'auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900'

  when:
      - ubuntu2004cis_rule_5_3_2
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.2 

```
